<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-SLPQU167" failures="1" tests="13" name="RegressionTestCases" time="0.328" errors="0" timestamp="2020-03-10T14:08:41 IST">
  <testcase classname="testNGPackage.Day4" name="Progression1" time="0.031"/>
  <testcase classname="testNGPackage.Day3" name="Prjct1Regression2" time="0.0"/>
  <testcase classname="testNGPackage.Day1" name="Demo" time="0.016"/>
  <testcase classname="testNGPackage.Day4" name="Progression2" time="0.0"/>
  <testcase classname="testNGPackage.Day3" name="Prjct2Regression3" time="0.031"/>
  <testcase classname="testNGPackage.Day4" name="Progression3" time="0.016"/>
  <testcase classname="testNGPackage.Day3" name="Prjct2Regression3" time="0.016"/>
  <testcase classname="testNGPackage.Day3" name="Prjct2Regression3" time="0.0"/>
  <testcase classname="testNGPackage.Day3" name="Prjct4Regression5" time="0.0"/>
  <testcase classname="testNGPackage.Day3" name="Prjct3Regression4" time="0.0"/>
  <testcase classname="testNGPackage.Day1" name="Demo2" time="0.14">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGPackage.Day1.Demo2(Day1.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo2 -->
  <testcase classname="testNGPackage.Day3" name="Prjct1Regression1" time="0.015"/>
  <testcase classname="testNGPackage.Day2" name="Demo3" time="0.016"/>
</testsuite> <!-- RegressionTestCases -->
